name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - numpy 
    - scipy
    - ipython
    - jupyter 
    - sympy 
    - nose
    - scikit-learn
